/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.catrina.ui;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.catrina.business.TransactionsOp;
import mx.itson.catrina.entities.Account;
import mx.itson.catrina.entities.Transaction;

/**
 *
 * @author José Alvarez
 */
public class FormAccount extends javax.swing.JFrame {
    //PRUEBA SUBIR PROYECTO
    //PRUEBA SUBIR PROYECTO SUBIR PROYECTO

    TransactionsOp operationTransaction = new TransactionsOp();
    String month;
    Account account;

    /**
     * Creates new form MainFrame
     */
    public FormAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPeriod = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTransaction = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStatement = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        cboMonth = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFinal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMessages = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));

        tblPeriod.setBackground(new java.awt.Color(204, 204, 255));
        tblPeriod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PERIOD SUMMARY", ""
            }
        ));
        jScrollPane4.setViewportView(tblPeriod);

        tblCustomer.setBackground(new java.awt.Color(204, 204, 255));
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "MARIO ABURTO"
            }
        ));
        jScrollPane1.setViewportView(tblCustomer);

        tblTransaction.setBackground(new java.awt.Color(204, 204, 255));
        tblTransaction.setForeground(new java.awt.Color(0, 0, 0));
        tblTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TRANSACTION ID", "DATE", "DESCRIPTION", "DEPOSITS", "WITHDRAWLS", "SUBTOTAL"
            }
        ));
        jScrollPane5.setViewportView(tblTransaction);

        tblStatement.setBackground(new java.awt.Color(204, 204, 255));
        tblStatement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "ACCOUNT STATEMENT"
            }
        ));
        jScrollPane2.setViewportView(tblStatement);

        jTextField1.setBackground(new java.awt.Color(102, 0, 204));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("ACCOUNT STATUS");

        cboMonth.setBackground(new java.awt.Color(153, 153, 255));
        cboMonth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboMonth.setForeground(new java.awt.Color(0, 0, 0));
        cboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janauary", "February", "March", "April", "May", "June", "July", "August", "September", "October ", "November ", "December " }));
        cboMonth.setToolTipText("");
        cboMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMonthItemStateChanged(evt);
            }
        });
        cboMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMonthActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Select month");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Select file");

        txtFinal.setText("jTextField2");

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("FINAL BALANCE");

        btnLoad.setBackground(new java.awt.Color(153, 153, 153));
        btnLoad.setForeground(new java.awt.Color(255, 255, 255));
        btnLoad.setText("Load File...");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        tblMessages.setBackground(new java.awt.Color(204, 204, 255));
        tblMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null}
            },
            new String [] {
                "Messages"
            }
        ));
        jScrollPane7.setViewportView(tblMessages);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMonthActionPerformed

    }//GEN-LAST:event_cboMonthActionPerformed


    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed

        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
            if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION);
            cboMonth.setEnabled(true);
            File file = fileChooser.getSelectedFile();
            byte fileByte[] = Files.readAllBytes(file.toPath());
            String content = new String(fileByte, StandardCharsets.UTF_8);
            account = new Account().deserialize(content);

            double Deposit = 0;
            double Withdrawal = 0;
            double total = 0;

            DefaultTableModel modelo = (DefaultTableModel) tblCustomer.getModel();
            modelo.setRowCount(0);
            modelo.addRow(new Object[]{"RFC: " + account.getCustomer().getRfc()});
            modelo.addRow(new Object[]{"" + account.getCustomer().getAddress()});
            modelo.addRow(new Object[]{account.getCustomer().getCity()});
            modelo.addRow(new Object[]{"Zip Code. " + account.getCustomer().getZipcode()});

            DefaultTableModel modelo1 = (DefaultTableModel) tblStatement.getModel();
            modelo1.setRowCount(0);
            modelo1.addRow(new Object[]{"Account: " + account.getAccount()});
            modelo1.addRow(new Object[]{"Clabe: " + account.getClabe()});
            modelo1.addRow(new Object[]{"Currency: " + account.getCurrency()});
            modelo1.addRow(new Object[]{"Previous_balance: " + account.getPreviousBalance()});

            month = cboMonth.getSelectedItem().toString();

            List<Transaction> trans = operationTransaction.Obtain(month, account.getTransactions());
            for (Transaction t : trans) {
                Deposit += t.getDeposit();
                Withdrawal += t.getWithDraw();
                total = t.getSubtotal();
            }

            DefaultTableModel modelo2 = (DefaultTableModel) tblPeriod.getModel();
            modelo2.setRowCount(0);
            modelo2.addRow(new Object[]{"Deposit", String.format("$%,34.2f", Deposit)});
            modelo2.addRow(new Object[]{"Withdrawal", String.format("$%,34.2f", Withdrawal)});
            modelo2.addRow(new Object[]{"Final Balance", String.format("$%,34.2f", total)});

            DefaultTableModel modelo3 = (DefaultTableModel) tblTransaction.getModel();
            modelo3.setRowCount(0);
            for (Transaction t : trans) {
                modelo3.addRow(new Object[]{
                    t.getTransactionId(),
                    t.getOperationDate(),
                    t.getOperationDescription(),
                    String.format("%+31.2f", t.getDeposit()),
                    String.format("%-31.2f", t.getWithDraw()),
                    String.format("%,35.2f", t.getSubtotal())
                });
            }
            
             DefaultTableModel model2 = (DefaultTableModel) tblMessages.getModel();
                    model2.setRowCount(0);
                    for (String s : account.getMessages()) {
                        model2.addRow(new Object[]{
                            s
                        });

                    }
           

            txtFinal.setText(String.format("%,+35.2f", total));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error Verifique Porfavor", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadActionPerformed

    private void cboMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMonthItemStateChanged

        try {

            double Deposit = 0;
            double Withdrawal = 0;
            double total = 0;
            month = cboMonth.getSelectedItem().toString();
            List<Transaction> trans = operationTransaction.Obtain(month, account.getTransactions());
            for (Transaction t : trans) {
                Deposit = t.getDeposit();
                Withdrawal = t.getWithDraw();
                total = t.getSubtotal();
            }

            DefaultTableModel modelo = (DefaultTableModel) tblPeriod.getModel();
            modelo.setRowCount(0);
            modelo.addRow(new Object[]{"Deposit", String.format("$%,34.2f", Deposit)});
            modelo.addRow(new Object[]{"Withdrawal", String.format("$%,34.2f", Withdrawal)});
            modelo.addRow(new Object[]{"Final Balance", String.format("$%,34.2f", total)});
            DefaultTableModel modelo3 = (DefaultTableModel) tblTransaction.getModel();
            modelo3.setRowCount(0);

            for (Transaction t : trans) {
                if (t.getDeposit() == 0) {
                    modelo3.addRow(new Object[]{t.getTransactionId(), t.getOperationDate(), t.getOperationDescription(), String.format("$%,31.2f", t.getWithDraw()), String.format("$%,31.2f", t.getAmount())});

                }
                if (t.getWithDraw() == 0) {
                    modelo3.addRow(new Object[]{t.getTransactionId(), t.getOperationDate(), t.getOperationDescription(), String.format("$%,31.2f", t.getDeposit()), String.format("%40s", "-"), String.format("$%,31.2f", t.getAmount())});

                }
            }
            txtFinal.setText(String.format("%,35.2f", total));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error Verifique Porfavor", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cboMonthItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JComboBox<String> cboMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTable tblMessages;
    private javax.swing.JTable tblPeriod;
    private javax.swing.JTable tblStatement;
    private javax.swing.JTable tblTransaction;
    private javax.swing.JTextField txtFinal;
    // End of variables declaration//GEN-END:variables
}
